version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  os_family: Linux
  task_size:
    mem_limit: 0.5GB
    cpu_limit: 256
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-3cda755b"
        - "subnet-d248e0fc"
      security_groups:
        - "sg-02f581083478d7e67"
      assign_public_ip: ENABLED